### PR TITLE
Node tf2

### PR DESCRIPTION
**Pull request by artivis**
Node uses tf2 rather than tf.

### CODE REVIEW

**Comment by artivis** [comment]
Travis fails on fetching `jade` release :  
`RuntimeError: Unknown release: 'jade'. Valid release names are: 'kinetic', 'indigo', 'lunar'`

**Comment by jvgomez** [comment]
Please correct me if I'm wrong, but when you include TF it already uses TF2, you can check the includes of TF [here](https://github.com/ros/geometry/tree/indigo-devel/tf/include/tf). AFAIK, this was done to keep total compatibility when migrating.

**Comment by artivis** [comment]
You are definitely right. This PR came after the need of handling an odd behavior with `tf` and static transforms which tf2 solves. I'm still investigating ...

**Comment by artivis** [comment]
The initial issue has roots in `static_tf`-related issue, especially with rosbags.  
This PR won't really fix it but it is the occasion to a slightly cleaner API and to move to `tf2`.

- Add option to try retrieving the tf X times
- Fix travis build related to `jade` pre-release as it is EOLed.  (`RuntimeError: Unknown release: 'jade'. Valid release names are: 'melodic', 'kinetic', 'indigo', 'lunar'`)

**Pull request merged**
